name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.0.4
  timeago: ^2.0.26
  feather_icons_flutter: ^4.7.4
  web_socket_channel: ^1.1.0

  mastodon_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
