name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^1.6.1
  timeago: ^2.0.10
  feather_icons_flutter: ^4.7.4
  web_socket_channel: ^1.0.9

  mastodon_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
