name: mastodon_flutter
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mastodon_dart: ^0.1.0+9
    # git: https://github.com/lukepighetti/mastodon-dart
    # path: ../mastodon-dart

  html: ^0.13.3+3
  shared_preferences: ^0.5.1+1
  url_launcher: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
