name: mastodon_flutter
description: A companion package to mastodon_dart that provides Flutter widgets to assist in developing a Mastodon Flutter client.
publish_to: 'none'
version: 0.3.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mastodon_dart:
    git:
      url: https://github.com/jtmuller5/mastodon_dart
  html: ^0.15.1
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.6
  flutter_feather_icons: ^2.0.0+1
  timeago: ^3.3.0
  stack_trace: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
